---
title: "R Notebook"
output: github_document
---
```{r}
library(tidyverse)
library(here)
library(e1071)
library(skimr)
library(lubridate)
library(forcats)
library(ggplot2)
sales <- readRDS(here::here("data/sales.rds"))
```

```{r}
# Chapter3: 2 different types of descriptive statistics: measures of the central tendency and measures of dispersion.

# 3.2 Central Tendency
mean(sales$floor_area_sqm) 
median(sales$floor_area_sqm)

# from https://stackoverflow.com/a/25635740
manual_mode <- function(x, na.rm = FALSE) { # we don't use 'mode' as a function name because it already exists
  if(na.rm){
    x = x[!is.na(x)]
  }
  ux <- unique(x)
  return(ux[which.max(tabulate(match(x, ux)))])
}

manual_mode(sales$floor_area_sqm)
```

```{r}
"Range"
max(sales$floor_area_sqm) - min(sales$floor_area_sqm)

"Interquartile Range"
IQR(sales$floor_area_sqm)

"Standard Deviation"
sd(sales$floor_area_sqm)

"Coefficient of variation"
sd(sales$floor_area_sqm) / mean(sales$floor_area_sqm)

"Kurtosis and Skewness from the 'e1071` library"
kurtosis(sales$floor_area_sqm)
skewness(sales$floor_area_sqm)
"Summary"
summary(sales$floor_area_sqm)
"Skim"
skim(sales$floor_area_sqm)
```

```{r}
ggplot(sales, aes(x = floor_area_sqm)) + 
  geom_histogram(binwidth = 5)
```

```{r}
ggplot(sales, aes(x = floor_area_sqm)) + 
  geom_histogram(aes(y = ..density..), binwidth = 5) +
  stat_function(fun = dnorm, args = list(mean = mean(sales$floor_area_sqm), sd = sd(sales$floor_area_sqm)))
```

```{r}
sales %>% 
  filter(floor_area_sqm == 67) %>% 
  View()
```

```{r}
ggplot(sales, aes(x = 1, y = floor_area_sqm)) + 
  geom_boxplot()
```

```{r}
ggplot(sales, aes(x = 1, y = floor_area_sqm)) + 
  geom_violin()
```
```{r}
ggplot(sales, aes(x = floor_area_sqm)) + 
  geom_histogram(binwidth = 10) +
  facet_wrap(vars(flat_type), scales = "free_y")
```

```{r}
ggplot(sales, aes(x = flat_type, y = floor_area_sqm)) + 
  geom_violin()
```

```{r}
# exploration of all variables in the dataset. 

#Summarize the different continuous variables (area, price, remaining lease) as well as the nominal/ordinal variables (month, flat_type, town, flat_model, storey_range), summarize these variables in both table (stats on central tendency and distribution) and visual form.

#Analyze the distribution of (some of) these variables for different subsets of the data. For example, explore the difference between towns, or between flat types.

#Analyze the distribution of at least one variable for unique combinations of town and flat_type (for each town, for each flat type: Ang Mo Kio, 1 room; Ang Mo Kio 2 room; etc.)

#Analyze change in resale price per square meter over time. Use a 6-month moving average to do so.
```
